In [1]:
import torch


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/anaconda3/envs/torch_env/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/usr/local/anaconda3/envs/torch_env/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/usr/local/anaconda3/envs/torch_env/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 739, in start
    s

In [2]:
scaler = torch.tensor(1)
scaler
print(scaler.ndim)
print(scaler.shape)

0
torch.Size([])


In [3]:
vec = torch.tensor([1,2,3])
vec
print(vec.ndim)
print(vec.shape)


1
torch.Size([3])


In [4]:
MAT = torch.tensor([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
MAT
print(MAT.ndim)
print(MAT.shape)


2
torch.Size([3, 3])


In [5]:
TEM = torch.tensor([[[1,2,3], [4,5,6], [7,8,9], [2,3,5]], 
                    [[2,3,4], [5,6,7], [7,8,9], [4, 1, 9]]])
print(TEM.ndim)
print(TEM.shape)


3
torch.Size([2, 4, 3])


In [6]:
RAND = torch.randint(low = 0, high = 100, size=(2,2,2), dtype=torch.int32)
RAND



tensor([[[63, 93],
         [ 1, 92]],

        [[39, 56],
         [ 5, 72]]], dtype=torch.int32)

In [7]:
ZEROES = torch.zeros(size=(4, 2, 3))
ZEROES

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [8]:
ARR = torch.arange(start=1, end=100, step=21)
ARR

tensor([ 1, 22, 43, 64, 85])

In [9]:
NEW = torch.zeros_like(ARR)
NEW

tensor([0, 0, 0, 0, 0])

In [10]:
#params

NEW2 = torch.randint(low=0, high=100, size=(4,3,2), dtype=torch.float32, device=None, requires_grad=False)
NEW2

tensor([[[73.,  8.],
         [26., 95.],
         [ 3., 43.]],

        [[57.,  6.],
         [12., 44.],
         [45., 14.]],

        [[78., 16.],
         [93., 62.],
         [72.,  0.]],

        [[22., 38.],
         [81., 38.],
         [72., 32.]]])

In [11]:
#float32 to float16
NEW3 = NEW2.type(torch.half)
NEW3

tensor([[[73.,  8.],
         [26., 95.],
         [ 3., 43.]],

        [[57.,  6.],
         [12., 44.],
         [45., 14.]],

        [[78., 16.],
         [93., 62.],
         [72.,  0.]],

        [[22., 38.],
         [81., 38.],
         [72., 32.]]], dtype=torch.float16)

In [12]:
print(NEW3.shape)
print(NEW3.ndim)
print(NEW3.dtype)
print(NEW3.device)



torch.Size([4, 3, 2])
3
torch.float16
cpu


In [13]:
NEW3 = torch.tensor([1,3,4])
print(NEW3)
print(NEW3 + 10)
print(NEW3 * 10)
print(NEW3 + 5 * 6)

tensor([1, 3, 4])
tensor([11, 13, 14])
tensor([10, 30, 40])
tensor([31, 33, 34])


In [14]:
NEW4 = torch.tensor([2,5,6])
print(torch.transpose(NEW4, -1, 0))


tensor([2, 5, 6])


In [15]:
NEW5 = torch.tensor([[1,2,3], [4,5,6]])
print(NEW5)
print(torch.transpose(NEW5, -1, 0))
print(torch.transpose(NEW5, 0, -1))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [16]:
NEW6 = torch.tensor([[7,8,9], [2,34,1]])
ans = torch.mm(NEW6, NEW5.T)
print(ans)

tensor([[ 50, 122],
        [ 73, 184]])


In [17]:
l = torch.arange(start=0, end=100, step=15)
print(l.min())
print(l.max())
print(l.type(torch.float32).mean())
print(l.median())
print(l.mode())
print(l.argmin())
print(l.argmax())
print(l)

tensor(0)
tensor(90)
tensor(45.)
tensor(45)
torch.return_types.mode(
values=tensor(0),
indices=tensor(0))
tensor(0)
tensor(6)
tensor([ 0, 15, 30, 45, 60, 75, 90])


In [18]:
reshape_t = torch.randint(low=2, high=20, size=(2,3,5))
print(reshape_t)
print(torch.reshape(input=reshape_t, shape=(5,2,3)))
new_reshape = torch.reshape(input=reshape_t, shape=(5,2,3))

tensor([[[12, 16,  7, 13, 10],
         [ 8,  9, 19, 12, 11],
         [ 3,  7,  2,  9, 14]],

        [[ 8, 16,  6,  2, 17],
         [ 7,  9, 12,  7, 10],
         [ 5,  2,  3, 13,  7]]])
tensor([[[12, 16,  7],
         [13, 10,  8]],

        [[ 9, 19, 12],
         [11,  3,  7]],

        [[ 2,  9, 14],
         [ 8, 16,  6]],

        [[ 2, 17,  7],
         [ 9, 12,  7]],

        [[10,  5,  2],
         [ 3, 13,  7]]])


In [19]:
print(reshape_t.ndim)
print(new_reshape.ndim)

3
3


In [20]:
new_reshape.view(1,5,6)

tensor([[[12, 16,  7, 13, 10,  8],
         [ 9, 19, 12, 11,  3,  7],
         [ 2,  9, 14,  8, 16,  6],
         [ 2, 17,  7,  9, 12,  7],
         [10,  5,  2,  3, 13,  7]]])

In [21]:
one = torch.randint(low=0, high=20, size=(1,2,1))
two = torch.randint(low=0, high=20, size=(1,2,1))
three = torch.randint(low=0, high=4, size=(1,2,1))
stack0 = torch.stack((one, two, three) , dim=0)
stack1 = torch.stack((one, two, three), dim=1)
stack2 = torch.stack((one, two, three), dim=2)
stack3 = torch.stack((one, two, three), dim=3)
print(one)
print(two)
print(three)
print(stack0)
print(stack1)
print(stack2)
print(stack3)

tensor([[[19],
         [18]]])
tensor([[[9],
         [0]]])
tensor([[[0],
         [2]]])
tensor([[[[19],
          [18]]],


        [[[ 9],
          [ 0]]],


        [[[ 0],
          [ 2]]]])
tensor([[[[19],
          [18]],

         [[ 9],
          [ 0]],

         [[ 0],
          [ 2]]]])
tensor([[[[19],
          [ 9],
          [ 0]],

         [[18],
          [ 0],
          [ 2]]]])
tensor([[[[19,  9,  0]],

         [[18,  0,  2]]]])


In [22]:
print(one)
torch.squeeze(one)

tensor([[[19],
         [18]]])


tensor([19, 18])

In [23]:
torch.unsqueeze(one, dim=2)

tensor([[[[19]],

         [[18]]]])

In [24]:
five = torch.randint(high=9, low=1, size=(2,3,4))
print(five)
print(five.shape)
print(torch.permute(five, dims=(2,0,1)).shape)

tensor([[[2, 1, 5, 4],
         [2, 5, 7, 1],
         [6, 3, 5, 4]],

        [[7, 5, 1, 6],
         [5, 6, 6, 6],
         [3, 8, 6, 2]]])
torch.Size([2, 3, 4])
torch.Size([4, 2, 3])


In [25]:
print(five[0])
print(five[0][0])
print(five[0][0][0])
print(five[0][0][0:2])

tensor([[2, 1, 5, 4],
        [2, 5, 7, 1],
        [6, 3, 5, 4]])
tensor([2, 1, 5, 4])
tensor(2)
tensor([2, 1])


In [26]:
import numpy as np
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 

In [27]:
np_array = np.random.rand(2,2,3)

In [30]:
ten = torch.tensor(np_array)
print(ten)

tensor([[[0.8263, 0.6316, 0.0554],
         [0.9567, 0.7622, 0.6471]],

        [[0.0500, 0.0271, 0.3843],
         [0.9859, 0.6403, 0.6439]]])
